### ISSUE TITLE
Info sign and severity not matching with the level of the log

### ISSUE THREAD

**Issue by realiceman** [googleapis/nodejs-logging-bunyan#238]
#### Environment details

  - OS: Ubuntu 18.04
  - Node.js version: 8.11.3
  - npm version: 6.4.1
  - `@google-cloud/logging-bunyan` version: 1.8.12

#### Steps to reproduce

  1.  Implement the code as per the doc says : 
     
```javascript
const loggingBunyan = new LoggingBunyan({
  projectId: projectId,
  keyFilename: 'keyfilenamePath.json'
});
logger = bunyan.createLogger({
        name: process.env.STACKDRIVER_CONTAINER_NAME,
        streams: [
          { stream: process.stdout, level: 'info' },
          loggingBunyan.stream('info')
        ]
});

logger.error('logger error initialized');
logger.info('logger info initialized');

```

  2.  Run the application and check inside Stackdriver GCP : 
![image003](https://user-images.githubusercontent.com/6204546/50261020-a3f3e480-03d8-11e9-8c6b-ae882a938839.png)

logger.error will always have the blue info sign but with a level at 50 and a severity at INFO.
So filtering the logs by the level is impossible at the meantime.

Thanks!

**Comment by ofrobots** [comment]
Hi @realiceman. I see that you are logging to the console in addition to streaming to the Bunyan Stackdriver stream. Both the console and the Bunyan streams are captured and available in the Stackdriver Logging UI. Make sure you are looking at the correct log destination.

Here's an example (the log name will be dependent on what how you named your Bunyan log, the default is `bunyan_log`):

![image](https://user-images.githubusercontent.com/79017/50301759-08e12600-043d-11e9-8e56-bc729c463c8f.png)

Note that the `insertId` field generated by this library has this unique pattern starting with `...`.

Can you make sure you are looking at the correct log stream in the UI?

**Comment by realiceman** [comment]
Hi @ofrobots , yes it is the correct destination. But unfortunately the blue info sign and severity are not matching the log level.  
Example : log.error("test");  , still blue info sign and severity marked at INFO level, but the key "level" is at 50.
thank you

**Comment by ofrobots** [comment]
@realiceman This is what I see running your code:

![image](https://user-images.githubusercontent.com/79017/50356118-c33c6000-0505-11e9-9777-8f5096b15024.png)

Looking at the `insertId` in your log screenshot, the insert id does not match the expected pattern for the logs generated by the `@google-cloud/logging-bunyan` stream. I still suspect that you are looking at the incorrect Log in the UI.

What environment are you deploying your application to? App Engine? GKE? GCE? For Kubernetes, you will have to make sure to select 'GKE container' in the first drop down, and then select 'bunyan_log' in the second drop down. If you cannot find these log destinations, can you provide screenshots of what you see in the first and second drop-down lists?

**Comment by realiceman** [comment]
Actually i followed the tutorial inside the npm page https://www.npmjs.com/package/@google-cloud/logging-bunyan and the sample on github . i've done the test again without "{stream: process.stdout}" and still i got the same issue.
Is there any chance you could publish your project "samples_express_applog" ?

**Comment by ofrobots** [comment]
@realiceman The `samples_express_applog` screenshot above was from the [express sample](https://github.com/googleapis/nodejs-logging-bunyan/blob/master/samples/express.js) in this repo deployed to App Engine standard.

Can you let me know where you are running your application? Is it running on Kubernetes, App Engine, Compute Engine, locally, or elsewhere?

**Comment by realiceman** [comment]
@ofrobots  Here is my scenario : 
the nodejs app is a docker image, deployed in GCP Kubernetes. So the logging works because it logs things, but not as well as it supposed to be like your sample app.

**Comment by ofrobots** [comment]
@realiceman Here's a screenshot bunyan app on GKE that I created using the sample you're following.

![image](https://user-images.githubusercontent.com/79017/50454174-9d92ca80-08fa-11e9-923e-4ee94e9f8620.png)

Please note the log name I have selected in the drop-downs. I am restricting only to the `bunyan_log`.

If you switch the view to `All logs` you will start seeing the automatically captured `stdout` and `stderr` in addition to the `@google-cloud/logging-bunyan` log stream. Note that the automatically captured `stdout` will not have the log levels recognized.

![image](https://user-images.githubusercontent.com/79017/50454252-21e54d80-08fb-11e9-92d4-de914c3f0534.png)

I've uploaded all the source code for the sample into this git repository (https://github.com/ofrobots/gke-bunyan-test). You should be able to deploy this into your own project to see this working.

Since everything is working correctly as far as I can still, I am going to close this issue. If you think there is a bug in the code or things are not working correctly, please add a comment and I can reopen the issue.
