### ISSUE TITLE
`message` field in data record overwrites actual log message

### ISSUE THREAD

**Issue by yelworc** [googleapis/nodejs-logging-bunyan#690]
When a `message` property is included in the log data payload (ie. the first parameter of the logger call, see example below), that field overrides the actual log message (provided as the second parameter). I realize that this might be hard to "fix" – the only ugly workaround I can think of at the moment would be automatically renaming the data field to something like `_message`…

If you consider this a user error, I think a caveat/warning in the docs would be appropriate.

#### Environment details

* OS: Debian 5.10.158-2
* Node.js version: v18.12.1
* npm version: 8.19.2
* @google-cloud/logging-bunyan version: 4.2.2

#### Steps to reproduce

1. Log a message like this: 

```javascript
logger.info({ message: 'boom' }, 'this is the actual message');
```

**Comment by cindy-peng** [comment]
Hi @yelworc , unfortunately this is the expected behavior for Nodejs-logging-bunyan library. `Nodejs-logging-bunyan` provides an easy to use layer for working with [Cloud Logging](https://cloud.google.com/logging/docs) using [Bunyan](https://www.npmjs.com/package/bunyan). For cloud logging, we try not to modify bunyan json log entries  to be consistent with other bunyan streams. That's why the provided `payload message` will still be logged as `jsonPayload.message` in Cloud logging.

I tried to repro the scenario here. The payload message field was actually not overwriting the `actual message`. If you use log explorer, you can expand the log entries and still find the actual message under `jsonPayload.msg`:
<img width="1203" alt="image" src="https://github.com/googleapis/nodejs-logging-bunyan/assets/148148319/b908b6c8-127e-4957-8ced-55c9a6299b17">

However when you view logs in log explorer,  logging uses `message key` from a structured log entry as the summary of the log entry when the entry isn't expanded: https://cloud.google.com/logging/docs/write-query-log-entries-gcloud#explore That's probably why it looks like the message has been overwritten. 

If you want to view both payload message and actual message without expanding the log entry, you can customize the summary to include both fields in log explorer:
<img width="1231" alt="image" src="https://github.com/googleapis/nodejs-logging-bunyan/assets/148148319/071dfe66-c982-40ed-bd89-52789fea3abc">

**Comment by yelworc** [comment]
Thx for the response @cindy-peng!

I noticed the `msg` field, but that feels somewhat inconsistent – it's _only_ there if the data payload contains a `message` property. Or, in fact, if it is an error:

```js
logger.info(new Error('boom'), 'something broke');
```

which results in the entire stack trace being used as the primary message, making the UI a bit confusing:

![2023-11-28 14 57 33 console cloud google com f00fbc9ef64b-obfuscated](https://github.com/googleapis/nodejs-logging-bunyan/assets/454308/63cf5991-ae32-40c8-afaf-9352f7e8df47)

But of course there are always going to be conflicts when mapping one data structure to another one, where both have their own "special" fields.

Is there a way to reconfigure what the GCL UI uses as the "primary" log message (i.e. the string it displays in unexpanded rows)? I think all I'd want would be for it to show `jsonPayload.msg` instead of `jsonPayload.message` if it exists :slightly_smiling_face:

**Comment by cindy-peng** [comment]
Thanks @yelworc! As you have already figured,`message` field is a special field for structured logging, along with other fields including `severity` and `labels`: https://cloud.google.com/logging/docs/structured-logging#special-payload-fields
https://cloud.google.com/functions/docs/monitoring/logging#processing_special_json_fields_in_messages
It is also by design to report the entire trace when there is an error, which is to allow [cloud error reporting](https://cloud.google.com/error-reporting/) to pick up errors:
https://github.com/googleapis/nodejs-logging-bunyan/blob/main/src/index.ts#L263

In GCL UI, we don't support customize for `primary` log message, only the `summary fields` can be customized: https://cloud.google.com/logging/docs/view/logs-explorer-interface#add_summary_fields.

Unfortunately in your case the only way to keep the `actual message` in the log entry line is to avoid overwriting those `special fields` in the payload. I will update the documentation to explain more about this.

**Comment by yelworc** [comment]
Thanks for the explanation! And your docs addition makes sense to me, FWIW :)
